### ISSUE TITLE
Hola, me aparece esto despues del jugador id 200. muchas gracias por darle seguimiento a este scraper

### ISSUE THREAD

**Issue by ericsantoyo** [alxgarci/marca-fantasy-api-scraper-updated#1]
![Screenshot 2023-02-12 162248](https://user-images.githubusercontent.com/82356498/218338017-96ee8f93-daec-4304-accb-9d4cc1031fd6.png)

**Comment by alxgarci** [comment]
Buenas! 
No estás usando fantasy_scraper.py que es el que he subido en este repositorio y actualizado! 
Estás usando el del otro usuario, ese error aquí lo solucioné yo!!
No sé si tu pregunta es sobre el scraper.py del otro proyecto y como se puede solucionar ese error?
Un saludo!

**Comment by ericsantoyo** [comment]
Toda la razon. Ya lo hice con la actualizacion. Es una pasada, millon de gracias

**Comment by alxgarci** [comment]
Nada!
Lo dicho, cualquier problema por aquí seguiré!
