### ISSUE TITLE
No puedo obtener el auth token

### ISSUE THREAD

**Issue by clujball** [alxgarci/marca-fantasy-api-scraper-updated#10]
Buenas chavales, intento obtener el auth token con la info que tenéis en el readme pero me indica esto:

```
VM1707:1 Uncaught TypeError: Cannot read properties of null (reading 'status')
    at <anonymous>:1:41
    
```
    Podéis especificar los pasos para obtener el auth token?

**Comment by alxgarci** [comment]
Buenas! El código actualmente no funciona, ya que ha desaparecido la interfaz web de laliga de relevo, en la 'issue' #7  están tirando del hilo para intentar sacar la información de los nuevos endpoints que usa la aplicación!
