### ISSUE TITLE
Consulta de clausulas en tu liga

### ISSUE THREAD

**Issue by dmoypal** [alxgarci/marca-fantasy-api-scraper-updated#5]
Muy bueno! , ¿sabes si existe la posibilidad de añadir información de tu liga? Precio de cláusulas y demás
Gracias!

**Comment by radamc** [comment]
Lo estuve probando en su momento pero no obtuve resultados

**Comment by alxgarci** [comment]
@dmoypal Hay ciertas cosas a las que sí se podría acceder, como plantillas de los usuarios de tu liga y alguna información, pero para implementarlo se necesita también bastante tiempo del que no dispongo de momento. 
Del precio de cláusulas no recuerdo si se podía ver. 

El rollo sería sacar los id's de usuario de cada usuario de la liga. La última vez que lo probé había algunas partes de ese mismo api endpoint que eran ya privadas. 
Intentaré implementarlas en algún momento libre pero todavía no prometo nada!

**Comment by alxgarci** [comment]
@dmoypal @radamc He subido nueva versión que también obtiene los datos de tu usuario, plantilla y de tu liga e integrantes. En principio se pueden consultar las cláusulas claro. Hay que seguir instrucciones nuevas del [README.md](https://github.com/alxgarci/marca-fantasy-api-scraper-updated#ejecucion-obtener-bearer-header) y se puede descargar la versión 1.5 en [releases](https://github.com/alxgarci/marca-fantasy-api-scraper-updated/releases/tag/1.5)

**Comment by dmoypal** [comment]
no tiene ningún sentido esto..., mil gracias, lo he probado y funciona perfecto!
