### ISSUE TITLE
Readme no está claro para la creación de ligas

### ISSUE THREAD

**Issue by acroscarrillo** [alxgarci/marca-fantasy-api-scraper-updated#6]
El readme reza:

> Para poder entrar en la API de nuestra liga/cuenta, necesitaremos un header que caduca cada 24hr. Se puede obtener fácilmente **_añadiento la siguiente página a marcadores e iniciando sesión_** en la propia página y luego pulsando en el marcador, lo que nos copiará en el portapapeles el token a pegar en terminal para poder acceder a las API de nuestra liga. Crear un nuevo marcador en la barra de marcadores, del nombre que sea y en URL introducimos:

Qué página? No lo logro ver en ningún lado. Quizá se podria aclarar esta sección?

A parte de eso, tremendo trabajo, sigue asi!!

**Comment by alxgarci** [comment]
Perdona que he estado un poco desconectado del proyecto, intentaré clarificarlo, pero básicamente me refiero a añadir un marcador al navegador, y en el marcador añadir la sección de javascript que se adjunta más abajo:

javascript: (function() {var text = JSON.parse(localStorage.getItem("auth")).status.authenticate.access_token;navigator.clipboard.writeText(text).then(function() {alert('Token copiado correctamente al portapapeles!');}, function(err) {alert('No se ha podido copiar el token: ', err);});})()

Lo modificaré en estos días, aún así, cualquier duda intentaré estar atento.

**Comment by alxgarci** [comment]
Me refiero realmente a esa parte de javascript con el término 'página', como se añade a marcadores, me bailaron las palabras.

**Comment by acroscarrillo** [comment]
Vale, para los demas: 

Efectivamente haces lo que se explica arriba **pero haces click al marcador estando dentro de la pagina de la liga!!**
Es un error trivial ahora que lo pienso pero merece la pena aclarar el `README.md`.

<img width="545" alt="Screenshot 2024-09-01 at 17 46 32" src="https://github.com/user-attachments/assets/8976c9cb-3e2a-4db6-aacb-12b7b4529b23">

**Me parece que esto ya no va a funcionar ahora que parece que han quitado el entrar con login en la web?** Igual hay algun work around con la api?

**Comment by alxgarci** [comment]
En principio en eso están en #7 , a ver si saco tiempo o si los compis lo sacan, simplemente es sacar los nuevos endpoints publicos y averiguar como va la autenticación para sacar la parte de cada uno de la liga.
