### ISSUE TITLE
Data historico?

### ISSUE THREAD

**Issue by acroscarrillo** [alxgarci/marca-fantasy-api-scraper-updated#8]
Estoy construyendo un modelo de ML y me preguntaba de donde puedo sacar el data de temporadas pasadas. Conservo todo el data de la anterior pero me gustaria poder tener unas 5 temporadas. 

Quizás lo podriamos subir aqui tambien !

**Comment by alxgarci** [comment]
En principio podría traer problemas por ser datos protegidos por (bastantes) derechos de autor, en su día lo pensé. Igualmente no sé si alguien ha guardado tantos datos de temporadas pasadas, personalmente yo solo tengo la última, y no sé por qué canal se deberían compartir, ya que peligraría este repositorio.

**Comment by acroscarrillo** [comment]
Gracias ! Me parece que igual se puede scrappear de paginas publicas como "https://www.futbolfantasy.com" pero habria que verlo.
